language: java
sudo: required

services:
  - docker

script: mvn clean package

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "us-east-1"  
  app: "reservation-system"
  env: "reservation-system-dev"
  bucket_name: "elasticbeanstalk-us-east-1-539409235947"
  on:
    branch: develop
